services:
  - type: web
    name: blms-backend
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Set this manually in Render dashboard
    autoDeploy: true
    healthCheckPath: /health
